### PR TITLE
Refactor player logic

### PR DESCRIPTION
**Pull request by hlixed**
Hahaha... It's just like you to make several if-statements in a row that all do the same thing. BUT NOT TODAY! Messy. Messy! MESSY! That code has too many if-statements for player direction, each doing nearly THE SAME THING, for over 16 CALS! Not good. NOT GOOD! It's time for a refactoring!

Haha! See this? 

sf2d_texture* tex_arr_friskWalk [4][4];

It's a multidimensional array! This code... Creates a 4-by-4 array of sf2d_texture*-s! MORE THAN JUST ONE! It makes me so MAD to see this code repitition! Us spectres can fit several ghosts into one little variable name, and we can then access them like so:

curr_tex = tex_arr_friskWalk[0][2];

Now, listen up. Listen up! LISTEN UP! I made the first array index represent the direction, and the 2nd index represent the frame, but you can make it WHATEVER YOU WANT! HAHAHA! tex_arr_friskWalk [0][2] is the 3rd frame (Remember! Arrays start from 0, human!) of the right-walking animation. Efficient, huh? Now you can plug in sprTimer into that last index like so:

curr_tex = tex_arr_friskWalk [0][(int)sprTimer];

and now all you have to do is update sprTimer! Efficiency. Efficiency. EFFICIENCY! And that's NOT ALL! For convenience, I also created a few VARIABLES like FRISK_RIGHT=0, so you can PLUG THEM INTO THE FIRST BRACKET! Hahaha! No need for remembering what each number represents, because that might lead to ERRORS:

curr_tex = tex_arr_friskWalk [FRISK_RIGHT][(int)sprTimer];

Beautiful. Beautiful! BEAUTIFUL! Look at how nice-looking that is! And all we did is OFFLOAD THOSE TEXTURES to the MULTIDIMENSIONAL ARRAY!

But. But! BUT! But when you start the program,YOU NEED TO CALL sfil_load_PNG_buffer()! Could this mean writing out 16 different sfil_load_PNG_buffer() calls? Never. Never! NEVER! Instead, we can use FOR LOOPS to access EVERY ELEMENT IN ORDER! HAHAHA!

	int i;
	int j;

	for (i=0;i<4;i++){ 
		for (j=0;j<4;j++){
			tex_arr_friskWalk[i][j] = sfil_load_PNG_buffer(friskFilenames[i][j], SF2D_PLACE_RAM);
		}
	}

Now, EVERYTHING is loaded! And we can use the same technique for sf2d_free_texture().

Now. Now! NOW! We have EFFICIENCY! It makes me SO GLAD! Now, WE HALVED THE SIZE OF THE CODE! HAHAHA!

if(playerDir == 0){
  		if (hsp == 0) {
			curr_tex = tex_arr_friskWalk[FRISK_RIGHT][0];
		}
		else {
			curr_tex = tex_arr_friskWalk[FRISK_RIGHT][(int)floor(sprTimer)];
		}
}
if(playerDir == 1){
....

Computers are dummies. That's why you've gotta TELL THEM what to DO! This works as long as sprTimer NEVER goes above 4. Ever. Ever! EVER!

Mad Dummy

**HEY, YOU!**

Who, me?

**YEAH, YOU!!! YOU'RE TRYIN' TO STEAL MY STYLE, HUH? Dummy. Dummy! DUMMY! YOU CAN GO FURTHER THAN THAT! Lemme show you. YOU'RE FIRED!**

**Foolish. Foolish! FOOLISH! We can do EVEN BETTER! You've got two "curr_tex =" calls per playerDir. Inefficient. Inefficient! INEFFICIENT! Those calls are doing the SAME THING WITH MINOR DIFFERENCES! YOU CAN REFACTOR!!**

**Dummy! Instead of just pasting in FRISK_RIGHT and FRISK_LEFT and all that, why not just plug in playerDir? Hahaha. Hahaha! HAHAHA! I DON'T NEED IF-STATEMENTS. I'VE GOT VARIABLES!!!**

	 if (hsp == 0) {
		curr_tex = tex_arr_friskWalk[playerDir][0];
	}
	else {
		curr_tex = tex_arr_friskWalk[playerDir][(int)floor(sprTimer)];
	}

**Now, you've only got TWO LINES of code! You're changing playerDir already, right? Reuse. Reuse! REUSE! Multidimensional arrays are for storing similar-typed data all together. The efficiency is MAD!**

**Alright, you're good to go. I'M OUTTA HERE!**

Oh, and you might eventually want to move the room data to something similar; look up structs if you want. Enjoy!

### CODE REVIEW

**Comment by lolzvid** [comment]
Well...

THAT'S AWESOME! XD

**Comment by lolzvid** [comment]
Also, If you want to join the FALLEN TEAM (currently me and Xavyrr), feel free to come in! :smiley:

**Comment by hlixed** [comment]
Right now I'm just periodically checking to see how the project is coming; thanks, though! Good luck on implementing more in the future!

(Oh, and if you find yourself with effectively copy-pasted code, you can probably refactor it. Almost always. Arrays, functions, and loops are amazing.)

**Comment by Xavyrr** [comment]
Can I just say that I love you? Ha-ha I'm just some self taught sorta programmer,  I learn new ways to do things all time. I knew about arrays, but I only used them for other things, I hadn't thought about using them to optimize code! I'll be sure to hit you up if I need help. :P Thanks!

**Comment by hlixed** [comment]
Don't worry about it whatsoever; even I'm still learning all the time (I 
can reply to the email I get from github to leave this reply; I just 
learned that!). Now take what you've learned, keep learning, and make 
something awesome!

Oh, and I made a mistake in the code actually; the line "if (hsp == 0) 
{" should be "if (hsp == 0 && vsp == 0) {", since you want to stop 
updating the sprites if we're not moving at all, but the old code will 
freeze you if you move sideways.

Good luck!

**Comment by Xavyrr** [comment]
It should actually be 
if (hsp == 0) {
   if (vsp == 0)
      //dostuff
   }
}
While this takes up more code, it's actually faster since it only does the first check, and then checks the second if the first is true. When they're combined it does both checks regardless even if the first check is false. ;)

**Comment by hlixed** [comment]
Nope! && is a [short-circuit 
operator](https://en.wikipedia.org/wiki/Short-circuit_evaluation), so if 
(hsp==0 && vsp==0) will automatically stop checking the 2nd operation if 
the first is false. || is also a short-circuit operator. You can even do 
things like if(divisor == 0 && mynum/divisor == 2) to avoid 
division-by-zero errors, for example.

**Comment by Xavyrr** [comment]
Whaaaaaaaaaaat.  MY LIFE IS A LIEEEEEEE! :'(

**Comment by hlixed** [comment]
Surprise! :)

You can even chain things like
if (vsp==0 && (keyUp || keyDown)){
and it will only evaluate what it needs to; if keyUp is true it won't 
check keyDown, and if vsp != 0 it won't check either of them.

**Pull request merged**
