### PR TITLE
Refactor rendering into a render() function

### PR DESCRIPTION
**Pull request by hlixed**
Howdy! I'm hlixed. You're new to GAME PROGRAMMING, aren'tcha? Golly, you must be so confused. Someone ought to teach you how things work around here! I guess little old me will have to do. ;)

See that text? That's your CODE, the very logic that governs your demo! But it's a bit inefficient. Four copies of the drawing code is a bit much, don't you think? That might even result in LAG! Down here, we eliminate LAG through... little white... "code refactorings!"

Instead of having sf2d_start_frame, sf2d_draw_texture, and  sf2d_end_frame () four times, we can move that into a render function to only do it once! I know the concept might seem like it won't change, but little old me already took care of that! I made a new VARIABLE named curr_tex, and instead of calling all those big scary functions so many times, render() will only do it once. 

Golly, isn't that convenient! Well, that's just how we do things here in GAME PROGRAMMING. ;)

### CODE REVIEW

**Comment by hlixed** [comment]
Hey, buddy? You missed this code refactoring. Let's try again, okay?

**Comment by hlixed** [comment]
Is this a joke?
Are you braindead?

**Comment by lolzvid** [comment]
Wow, great job there! I was looking yesterday by optimizing some code, but you did it much quicker!

I'll merge this pull request (and yes, I'm not that much experienced with 3DS C coding).

**Comment by hlixed** [comment]
No problem!

By the way, one way of doing simple animation is to have a timer that gets +=1'd each frame, and then just have something like if(timer > 60){timer=0;//switch to next frame based on player direction}. [this](http://gameprogrammingpatterns.com/contents.html) is a really great ebook that outlines a lot of things some games use (admittedly, most of them won't even be necessary here whatsoever, but it might be good to just be aware of some of them; the input method in particular. DO NOT FEEL OBLIGATED TO USE ANY OF THEM.)

Have fun!

**Comment by lolzvid** [comment]
I was trying to use timers earlier, but it seems like that it fails to compile (even including "time.h"). Is it my bad usage, or is it a code environment problem?

**Comment by hlixed** [comment]
I don't know! Maybe time.h is something to do with the 3ds's clock or something. I was just suggesting timer as an int variable.

**Comment by lolzvid** [comment]
Thanks, but I prefer having all the files present if is there any needs for them. :smile:

**Comment by hlixed** [comment]
Uh; I think you're getting mixed up. I was just proposing to have one 
variable that counts up repeatedly and is then set to 0 when it reaches 
a certain point; you don't need time.h unless you want to know what 
hour/minute/second it is according to the DS's clock.

**Comment by lolzvid** [comment]
I've just updated the .gitignore file, excluding the build directory (I don't know if it worked, or not).

**Comment by hlixed** [comment]
Looks good; next time you run 'make clean' and 'make', git will record you deleting the build folder and then never commit the build folder ever again. Have a nice day!

**Comment by lolzvid** [comment]
Thanks! :smiley:

**Pull request merged**
